productStore:
    path:      /
    defaults:  { _controller: app.product_controller:showAction }

productStore:
    path:      /create
    defaults:  { _controller: app.product_controller:createAction }
