# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
  locale: en

services:
  app.product_service:
    class: AppBundle\Service\ProductService
    arguments: ['@doctrine.orm.entity_manager']
  app.product_controller:
    class: AppBundle\Controller\ProductController
    arguments: ['@app.product_service']
  app.product_post_data_to_product_converter:
    class: AppBundle\Request\ParamConverter\productPostDataToProductConverter
    tags:
      - { name: request.param_converter, priority: 0, converter: app.productPostDataToProductConverter }