# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  app.productService:
    class: AppBundle\Service\ProductService
    arguments: [@doctrine.orm.entity_manager]
  app.productController:
    class: AppBundle\Controller\ProductController
    arguments: [@app.productService]
  app.productPostDataToProductConverter:
    class: AppBundle\Request\ParamConverter\productPostDataToProductConverter
    tags:
      - { name: request.param_converter, priority: 0, converter: app.productPostDataToProductConverter }