services:
    app.tokens.action_listener:
        class: AppBundle\EventListener\TokenListener
        arguments: ['%tokens%']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    app.product_service:
        class: AppBundle\Service\ProductService
        arguments: ["@doctrine.orm.entity_manager"]
    app.product_controller:
        class: AppBundle\Controller\ProductController
        arguments: ["@app.product_service", "@templating"]

